package com.verdant.core.genui.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Root layout descriptor generated by the LLM. Each daily generation produces
 * one of these, cached in Supabase and rendered by [DynamicDashboard].
 */
@Serializable
data class DashboardLayout(
    val version: Int = 1,
    @SerialName("generated_at") val generatedAt: Long,
    @SerialName("expires_at") val expiresAt: Long,
    val title: String? = null,
    val sections: List<DashboardSection>,
)

@Serializable
data class DashboardSection(
    val id: String,
    val component: ComponentType,
    val span: SpanType = SpanType.FULL,
    val config: ComponentConfig = ComponentConfig(),
    @SerialName("data_source") val dataSource: DataSourceRef = DataSourceRef(source = DataSource.STATIC),
    val priority: Int = 0,
    val condition: DisplayCondition? = null,
)

@Serializable
enum class ComponentType {
    @SerialName("today_habits") TODAY_HABITS,
    @SerialName("progress_ring") PROGRESS_RING,
    @SerialName("category_nav") CATEGORY_NAV,
    @SerialName("activity_recap") ACTIVITY_RECAP,
    @SerialName("stat_card") STAT_CARD,
    @SerialName("finance_summary") FINANCE_SUMMARY,
    @SerialName("ai_predictions") AI_PREDICTIONS,
    @SerialName("life_dashboard") LIFE_DASHBOARD,
    @SerialName("insight_text") INSIGHT_TEXT,
    @SerialName("streak_highlight") STREAK_HIGHLIGHT,
    @SerialName("contribution_grid") CONTRIBUTION_GRID,
    @SerialName("mood_summary") MOOD_SUMMARY,
    @SerialName("health_snapshot") HEALTH_SNAPSHOT,
    @SerialName("stat_row") STAT_ROW,
    @SerialName("category_grid") CATEGORY_GRID,
}

@Serializable
enum class SpanType {
    @SerialName("full") FULL,
    @SerialName("half") HALF,
}

@Serializable
data class ComponentConfig(
    val title: String? = null,
    val subtitle: String? = null,
    @SerialName("background_color") val backgroundColor: String? = null,
    @SerialName("icon_color") val iconColor: String? = null,
    val icon: String? = null,
    @SerialName("max_items") val maxItems: Int? = null,
    @SerialName("show_refresh_button") val showRefreshButton: Boolean? = null,
    @SerialName("stat_label") val statLabel: String? = null,
    @SerialName("stat_unit") val statUnit: String? = null,
    val children: List<DashboardSection>? = null,
    @SerialName("insight_text") val insightText: String? = null,
    @SerialName("habit_id") val habitId: String? = null,
    @SerialName("navigate_to") val navigateTo: String? = null,
)

@Serializable
data class DataSourceRef(
    val source: DataSource,
    val filters: Map<String, String> = emptyMap(),
    val fields: List<String> = emptyList(),
)

@Serializable
enum class DataSource {
    @SerialName("habits_today") HABITS_TODAY,
    @SerialName("habits_completion") HABITS_COMPLETION,
    @SerialName("streaks") STREAKS,
    @SerialName("transactions_monthly") TRANSACTIONS_MONTHLY,
    @SerialName("predictions_active") PREDICTIONS_ACTIVE,
    @SerialName("ai_insights_recent") AI_INSIGHTS_RECENT,
    @SerialName("emotional_latest") EMOTIONAL_LATEST,
    @SerialName("health_summary_7d") HEALTH_SUMMARY_7D,
    @SerialName("life_scores") LIFE_SCORES,
    @SerialName("player_profile") PLAYER_PROFILE,
    @SerialName("static") STATIC,
    @SerialName("habit_entries") HABIT_ENTRIES,
}

@Serializable
data class DisplayCondition(
    val field: String,
    val operator: String,
    val value: String,
)
